version: '3.8'
services:
  backend:
    build:
      context: .
      dockerfile: app/Dockerfile
    ports:
      - "8080:8080"
    container_name: prospera-backend
    env_file:
      - ./.env # Pointing to the .env file in the root directory

  frontend:
    build:
      context: .
      dockerfile: prospera-app/Dockerfile
    ports:
      - "3000:80" # Mapping port 80 of NGINX to localhost:3000
    container_name: prospera-frontend
    environment:
      - REACT_APP_API_URL=http://backend:8080
    depends_on:
      - backend
